# Generated by Django 4.0 on 2022-01-05 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cat_banner',
            field=models.ImageField(blank=True, upload_to='covers/photos'),
        ),
    ]
